# Basic Python Operations and Libraries

- Bit-manipulation
- Numpy
- Pandas
- Itertool
- write txt

# write txt

In [11]:
textfile = open('./result.txt', "w")
a = [('1',),('2',),('5',)]
for b in a:
    textfile.write(str(b))
# textfile.write(str(a))

# Bit-manipulation

In [16]:
# generate the bit of 4 and -3
print(bin(4))
print(bin(-4))

0b100
-0b100


In [17]:
# 按二进制位数左移
0b11 << 2 

12

In [18]:
# 按位与
4 & 2

0

In [8]:
4 & -4

4

In [12]:
3 & (-3)

1

In [19]:
# 4 - 0100
# 4 反码 - 1011
# 4 补码 - 1011+1 = 1100 逢二进一
# 0100 & 1100 = 0100 = 4 
# power 等于 2 的十进位的判断条件可以用 x&(-x) == x来处理

# Itertool

- https://docs.python.org/3/library/itertools.html

In [11]:
from itertools import combinations,permutations

In [21]:
it = iter([1,2,3,4,2])

In [34]:
def solution(A):
    count = 0
    for i in A:
        if (abs(i)>9) & (abs(i)<100):
            count += i
    return count

In [45]:
import numpy as np

solution(np.array([1,1000,80,-91]))

-11

In [46]:
solution([47,1900,1,90,45])

182

In [47]:
solution([-13,1900,1,100,45])

32

In [48]:
set =1 

In [49]:
set

1

In [1]:
set([1,2,3,3])

{1, 2, 3}

In [4]:
list(combinations(['1','2','3'],2))

[('1', '2'), ('1', '3'), ('2', '3')]

In [4]:
tp = (('1'),('4'),('2'),('3'))

In [15]:
tp = [('1','2','5','6'),('2','3','5','6'),('1','4','5','6')]

In [16]:
tp 

[('1', '2', '5', '6'), ('2', '3', '5', '6'), ('1', '4', '5', '6')]

In [27]:
list(combinations(['1','2','3'],2))

[('1', '2'), ('1', '3'), ('2', '3')]

In [41]:
set(list(sorted(set(('1','2')).union(set(('2','3')))))).issubset(['1','2','3'])

True

In [46]:
list(combinations(('101', '105', '110', '115', '98'),4))

[('101', '105', '110', '115'),
 ('101', '105', '110', '98'),
 ('101', '105', '115', '98'),
 ('101', '110', '115', '98'),
 ('105', '110', '115', '98')]

In [7]:
int(''.join(('1', '2'))) % 1000

12

In [76]:
list(set([('1','3'),('1','3'),('2','3')]))

[('1', '3'), ('2', '3')]

# Numpy

- dtype, empty, zeros, arrange
- dot, comsum
- .T, reshape, transpose

In [1]:
import numpy as np
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2, dtype=np.float64)
arr2
# arr2.ndim 2
# arr2.shape (2,4)
# arr.astype(np.float64)

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [5]:
np.empty((2, 3, 3))

array([[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
        [1.60219442e-306, 1.89146896e-307, 1.37961302e-306],
        [1.05699242e-307, 8.01097889e-307, 1.78020169e-306]],

       [[7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
        [2.22522597e-306, 1.69119330e-306, 1.02360867e-306],
        [1.60220528e-306, 1.78019082e-306, 1.42410974e-306]]])

In [6]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
np.empty(10)

array([0.00000000e+000, 0.00000000e+000, 1.38338381e-322, 1.33621605e-311,
       4.94065646e-324, 0.00000000e+000, 3.39519327e-313, 7.90505033e-323,
       1.33624731e-311, 1.33624731e-311])

In [9]:
# dot
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
np.dot(x, y)

array([[19, 22],
       [43, 50]])

In [16]:
# reshape
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
np.array([3, 4, 5, 6, 7, 8]).reshape(6, 1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [17]:
arr.sum(axis=0)

array([15, 18, 21, 24, 27])

In [10]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [12]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [14]:
arr.transpose((1, 0, 2)) # change the axes order from 0,1,2 to 1,0,2 : 
# ,!arr[x][y][z]=arr[y][x][z]

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [18]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [1]:
import numpy as np
array = np.array([[1,2], [3,4], [5,6]])
array2 = np.append(array, [[1],[1],[1]], axis = 1)
array2

array([[1, 2, 1],
       [3, 4, 1],
       [5, 6, 1]])

In [5]:
array = np.array([[1,2], [3,4], [5,6]])
array2 = np.append(array, np.array([1,1,1]).reshape(-1,1), axis = 1)
array2

array([[1, 2, 1],
       [3, 4, 1],
       [5, 6, 1]])

In [28]:
array = np.array([[1,2], [3,4], [5,6]])
array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
np.where(array[:,-1] < 5, True, False)

array([ True,  True, False])

In [35]:
array[np.where(array[:,1] < 5),:]

array([[[1, 2],
        [3, 4]]])

In [36]:
array[np.where(array[:,1] < 5,False,True),:]

array([[5, 6]])

In [41]:
array.shape

(3, 2)

In [43]:
np.mean(array,axis=0)

array([3., 4.])

In [25]:
np.square(array)

NameError: name 'array' is not defined

In [32]:
np.array([1,2,None])

array([1, 2, None], dtype=object)

# Pandas

- missing value
- map categorical varibles

In [1]:
import pandas as pd
from io import StringIO
csv_data = \
'''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,'''
df = pd.read_csv(StringIO(csv_data))
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [ ]:
df.isnull().sum()
# dropna - column
df.dropna(axis=1)
# drop rows that have less than 4 real values
df.dropna(thresh=4)
# only drop rows where NaN appear in specific columns (here: 'C')
df.dropna(subset=['C'])

In [2]:
df = pd.DataFrame([['green', 'M', 10.1, 'class1'],
['red', 'L', 13.5, 'class2'],
['blue', 'XL', 15.3, 'class1']])
df.columns = ['color', 'size', 'price', 'classlabel']
df

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

In [4]:
size_mapping = {'XL': 3,
'L': 2,
'M': 1}
df['size'] = df['size'].map(size_mapping)
df

color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1

In [5]:
inv_size_mapping = {v: k for k, v in size_mapping.items()}
df['size'].map(inv_size_mapping)

0     M
1     L
2    XL
Name: size, dtype: object

In [2]:
float(5.0) == int(5)

True